# ============================================================
# Agent 6 - Supply Chain Risk Decision Report
# Agent 5 Risk Assessment -> Final Decision Support Report
# ============================================================

import os
import json
from pathlib import Path
from openai import OpenAI


# ============================================================
# 1. 기본 설정
# ============================================================

INPUT_FILE = os.getenv(
    "AGENT5_INPUT",
    "agent5_risk_assessment.json"
)

OUTPUT_FILE = os.getenv(
    "AGENT6_OUTPUT",
    "agent6_final_report.json"
)

TOP_N = int(os.getenv("AGENT6_TOP_N", "10"))

client = OpenAI(
    api_key=os.environ["OPENAI_API_KEY"]
)


# ============================================================
# 2. JSON 읽기
# ============================================================

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# ============================================================
# 3. Agent 5 결과 정리
# ============================================================

def prepare_risk_data(data):

    results = data.get("results", [])

    # risk_score 기준 내림차순
    results = sorted(
        results,
        key=lambda x: x.get("risk_score", 0),
        reverse=True
    )

    # 상위 위험 supplier
    top_results = results[:TOP_N]

    # Risk level별 개수
    level_count = {
        "HIGH": 0,
        "MEDIUM": 0,
        "LOW": 0
    }

    for item in results:
        level = item.get("risk_level", "LOW")

        if level in level_count:
            level_count[level] += 1

    # 최고 위험 supplier
    highest = top_results[0] if top_results else {}

    return {
        "agent5_method": data.get("method"),
        "supplier_count": data.get("supplier_count"),
        "thresholds": data.get("thresholds"),
        "weights": data.get("weights"),

        "risk_level_distribution": level_count,

        "highest_risk_supplier": highest,

        "top_risk_suppliers": top_results
    }


# ============================================================
# 4. Prompt 생성
# ============================================================

def create_prompt(risk_data):

    return f"""
You are Agent 6, a Supply Chain Risk Decision Support Agent.

Your role is NOT to calculate a new risk score.

Your role is to interpret the results generated by Agent 5
and create a final report that helps a human decision-maker
understand the supply chain risk and determine what should
be investigated or monitored.

IMPORTANT RULES:

1. Do NOT invent news, events, companies, countries,
   products, suppliers, or supply-chain relationships.

2. Use ONLY the information provided in the input.

3. Do NOT change the Agent 5 risk scores.

4. Do NOT recalculate the risk score.

5. Clearly distinguish between:
   - confirmed information
   - risk interpretation
   - questions that require human verification

6. Recommended actions must be presented as
   decision-support suggestions, not as automatically
   executed actions.

7. If information is missing, explicitly state:
   "Information not available in Agent 5 data."

8. The report is intended for a human supply-chain
   decision maker.

Agent 5 information:

{json.dumps(risk_data, ensure_ascii=False, indent=2)}

Create the output using exactly this JSON structure:

{{
  "agent": "Agent 6",
  "report_type": "Supply Chain Risk Decision Report",

  "executive_summary": {{
    "overall_assessment": "",
    "highest_risk_supplier": "",
    "highest_risk_score": 0,
    "risk_level": "",
    "affected_companies": []
  }},

  "risk_assessment": {{
    "risk_score": 0,
    "risk_level": "",
    "exposure_breadth": 0,
    "dependency_ratio": 0,
    "centrality": 0,
    "exposure_depth": 0,
    "assessment_basis": ""
  }},

  "main_risk_factors": [],

  "affected_supply_chain": [
    {{
      "supplier": "",
      "connected_companies": [],
      "path_count": 0,
      "exposure_depth": 0
    }}
  ],

  "news_evidence": [],

  "risk_exposure_questions": [],

  "recommended_actions": {{
    "immediate": [],
    "short_term": [],
    "monitoring": []
  }},

  "decision_summary": ""
}}

Return JSON only.
"""


# ============================================================
# 5. OpenAI 호출
# ============================================================

def generate_report(risk_data):

    prompt = create_prompt(risk_data)

    response = client.chat.completions.create(
        model=os.getenv(
            "OPENAI_MODEL",
            "gpt-5.6"
        ),
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a supply chain risk analyst. "
                    "Return valid JSON only."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.2
    )

    content = response.choices[0].message.content

    # 혹시 ```json ``` 형태로 반환될 경우 처리
    if content.startswith("```"):
        content = content.replace("```json", "")
        content = content.replace("```", "")
        content = content.strip()

    return json.loads(content)


# ============================================================
# 6. 결과 저장
# ============================================================

def save_report(report):

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            report,
            f,
            ensure_ascii=False,
            indent=2
        )


# ============================================================
# 7. Main
# ============================================================

def main():

    print("=" * 60)
    print("Agent 6 - Final Risk Report")
    print("=" * 60)

    print(f"Input : {INPUT_FILE}")
    print(f"Output: {OUTPUT_FILE}")

    # Agent 5 결과 읽기
    agent5_data = load_json(INPUT_FILE)

    # Agent 5 결과 정리
    risk_data = prepare_risk_data(agent5_data)

    print("\n[Risk Summary]")

    print(
        "Supplier Count:",
        risk_data["supplier_count"]
    )

    print(
        "Risk Distribution:",
        risk_data["risk_level_distribution"]
    )

    highest = risk_data["highest_risk_supplier"]

    if highest:
        print(
            "Highest Risk Supplier:",
            highest.get("supplier_name")
        )

        print(
            "Risk Score:",
            highest.get("risk_score")
        )

        print(
            "Risk Level:",
            highest.get("risk_level")
        )

    # Agent 6 보고서 생성
    report = generate_report(risk_data)

    # 저장
    save_report(report)

    print("\nAgent 6 report generated successfully.")

    print(
        f"Saved to: {OUTPUT_FILE}"
    )


if __name__ == "__main__":
    main()
