name: GDELT Monitoring

on:
  schedule:
    - cron: '0 * * * *'   # 매시간
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install
        run: pip install -r requirements.txt

      - name: run python
        run: python gdelt_monitoring.py

      - name: commit json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add gdelt_results.json

          git commit -m "update gdelt results" || echo "no changes"

          git push
